"""
Twitch Content Pipeline — Video Generator Service
Runs free on Render.com (512MB RAM limit).

Flow: script + topic -> TTS audio -> FFmpeg (color bg + captions) -> MP4
No Pexels download needed — uses ffmpeg built-in color source.
"""
from flask import Flask, jsonify, send_file, request, abort
from gtts import gTTS
import subprocess, json, os, uuid, threading, shutil, re, time

app = Flask(__name__)

OUTPUT_DIR = "/tmp/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

jobs = {}
jobs_lock = threading.Lock()


# --- Helpers ------------------------------------------------------------------

def get_audio_duration(path):
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_streams", path],
        capture_output=True, text=True
    )
    data = json.loads(result.stdout)
    for stream in data.get("streams", []):
        if "duration" in stream:
            return float(stream["duration"])
    raise RuntimeError("Could not determine audio duration")


def generate_srt(script, duration):
    """Split script into timed caption chunks and produce SRT content."""
    clean = re.sub(r'\([^)]*\)', '', script).strip()
    words = clean.split()
    WORDS_PER_CHUNK = 6
    chunks = []
    for i in range(0, len(words), WORDS_PER_CHUNK):
        chunks.append(" ".join(words[i:i + WORDS_PER_CHUNK]))
    if not chunks:
        chunks = [clean[:80]]
    time_per_chunk = duration / len(chunks)
    srt = ""
    for i, chunk in enumerate(chunks):
        start = i * time_per_chunk
        end = min((i + 1) * time_per_chunk, duration)
        srt += f"{i + 1}\n{fmt_time(start)} --> {fmt_time(end)}\n{chunk}\n\n"
    return srt


def fmt_time(sec):
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = sec % 60
    ms = int((s - int(s)) * 1000)
    return f"{h:02d}:{m:02d}:{int(s):02d},{ms:03d}"


def assemble_video(audio_path, srt_path, output_path, duration):
    """
    Low-memory FFmpeg pipeline:
    - Background: solid dark color generated by ffmpeg (no video download)
    - Resolution: 720x1280 portrait (saves memory vs 1080p)
    - Captions: burned-in from SRT
    - Preset: ultrafast (low CPU/memory)
    """
    srt_escaped = srt_path.replace("\\", "/").replace(":", "\\:")

    vf = (
        f"subtitles='{srt_escaped}':force_style='"
        "FontName=Arial,"
        "FontSize=22,"
        "Bold=1,"
        "PrimaryColour=&H00FFFFFF&,"
        "OutlineColour=&H00000000&,"
        "Outline=3,"
        "Shadow=0,"
        "Alignment=2,"
        "MarginV=100"
        "'"
    )

    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", f"color=c=0x0d0d1a:size=720x1280:rate=24",
        "-i", audio_path,
        "-vf", vf,
        "-c:v", "libx264",
        "-preset", "ultrafast",
        "-crf", "28",
        "-c:a", "aac",
        "-b:a", "96k",
        "-t", str(duration + 0.5),
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        output_path
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"FFmpeg failed:\n{result.stderr[-2000:]}")


# --- Background processing ---------------------------------------------------

def process_video_job(job_id, script, topic):
    work_dir = f"/tmp/job_{job_id}"
    os.makedirs(work_dir, exist_ok=True)
    output_path = f"{OUTPUT_DIR}/{job_id}.mp4"

    try:
        with jobs_lock:
            jobs[job_id]["status"] = "generating_audio"

        # 1. TTS
        audio_path = f"{work_dir}/audio.mp3"
        tts = gTTS(text=script, lang="en", slow=False)
        tts.save(audio_path)
        duration = get_audio_duration(audio_path)

        with jobs_lock:
            jobs[job_id]["status"] = "generating_captions"

        # 2. SRT captions
        srt_content = generate_srt(script, duration)
        srt_path = f"{work_dir}/captions.srt"
        with open(srt_path, "w", encoding="utf-8") as f:
            f.write(srt_content)

        with jobs_lock:
            jobs[job_id]["status"] = "assembling_video"

        # 3. FFmpeg: color bg + captions + audio
        assemble_video(audio_path, srt_path, output_path, duration)

        with jobs_lock:
            jobs[job_id]["status"] = "done"
            jobs[job_id]["path"] = output_path

    except Exception as e:
        with jobs_lock:
            jobs[job_id]["status"] = f"error: {str(e)}"
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


# --- Routes ------------------------------------------------------------------

@app.route("/health")
def health():
    return jsonify({"status": "ok"})


@app.route("/status/<path:job_id>")
def status(job_id):
    with jobs_lock:
        job = jobs.get(job_id)
    if not job:
        return jsonify({"status": "not_found", "job_id": job_id}), 404
    return jsonify({"job_id": job_id, "status": job["status"]})


@app.route("/generate", methods=["POST"])
def generate():
        data = request.get_json(force=True) or request.form.to_dict() or {}
    script = (data.get("script") or "").strip()
    topic = (data.get("topic") or "gaming").strip()

    if not script:
        return jsonify({"error": "script is required"}), 400

    job_id = uuid.uuid4().hex[:10]
    with jobs_lock:
        jobs[job_id] = {"status": "queued", "path": None}

    t = threading.Thread(target=process_video_job, args=(job_id, script, topic), daemon=True)
    t.start()

    return jsonify({
        "job_id": job_id,
        "status_url": f"/status/{job_id}",
        "download_url": f"/download/{job_id}"
    }), 202


@app.route("/download/<job_id>")
def download(job_id):
    """Polls internally until video is ready, then streams it."""
    for _ in range(120):  # wait up to 4 minutes
        with jobs_lock:
            job = jobs.get(job_id)
        if not job:
            abort(404)
        s = job["status"]
        if s == "done" and job["path"] and os.path.exists(job["path"]):
            return send_file(
                job["path"],
                mimetype="video/mp4",
                as_attachment=True,
                download_name=f"twitch_video_{job_id}.mp4"
            )
        if s.startswith("error"):
            return jsonify({"error": s}), 500
        time.sleep(2)
    return jsonify({"error": "timeout waiting for video"}), 504

@app.route("/tos")
def tos():
        return """<!DOCTYPE html><html><head><title>Terms of Service</title></head><body>
        <h1>ClipLoreTV Auto-Post — Terms of Service</h1>
        <p>This application is a private automation tool used solely by its owner to upload
        video content to TikTok. It is not a public-facing service and has no end users
        other than the developer. By using this tool you agree to TikTok's own Terms of
        Service at https://www.tiktok.com/legal/terms-of-service.</p>
        <p>Last updated: 2026-03-03</p>
        </body></html>""", 200, {"Content-Type": "text/html"}


@app.route("/privacy")
def privacy():
        return """<!DOCTYPE html><html><head><title>Privacy Policy</title></head><body>
        <h1>ClipLoreTV Auto-Post — Privacy Policy</h1>
        <p>This application is a private automation tool. It does not collect, store, or
        share personal data from any users. The only data processed is video content
        created by the tool owner and uploaded to TikTok on their behalf via the
        TikTok Content Posting API.</p>
        <p>TikTok access tokens are used solely to authenticate API requests and are
        never logged or shared with third parties.</p>
        <p>Last updated: 2026-03-03</p>
        </body></html>""", 200, {"Content-Type": "text/html"}


@app.route("/tiktok/callback")
def tiktok_callback():
        """OAuth2 callback — exchanges code for access token."""
        code = request.args.get("code")
        if not code:
                    return jsonify({"error": "missing code"}), 400
                # Store code temporarily so user can copy it
    return jsonify({"message": "Authorization successful", "code": code}), 200


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
